/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SocialMediaLinks = IDL.Record({
  'tiktok' : IDL.Opt(IDL.Text),
  'twitter' : IDL.Opt(IDL.Text),
  'instagram' : IDL.Opt(IDL.Text),
  'others' : IDL.Opt(IDL.Vec(IDL.Text)),
  'facebook' : IDL.Opt(IDL.Text),
  'youtube' : IDL.Opt(IDL.Text),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CreatorProfile = IDL.Record({
  'id' : IDL.Principal,
  'instagramFollowers' : IDL.Nat,
  'youtubeSubscribers' : IDL.Nat,
  'pricingPost' : IDL.Nat,
  'pricingReel' : IDL.Nat,
  'createdAt' : IDL.Int,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'socialMediaLinks' : SocialMediaLinks,
  'category' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'profilePicture' : IDL.Opt(ExternalBlob),
  'pricingVideo' : IDL.Nat,
  'tiktokFollowers' : IDL.Opt(IDL.Nat),
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const CollaborationRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  }),
  'creator' : IDL.Principal,
  'createdAt' : IDL.Int,
  'campaignDetails' : IDL.Text,
  'brand' : IDL.Principal,
});
export const PaymentTransaction = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  }),
  'createdAt' : IDL.Int,
  'sender' : IDL.Principal,
  'amount' : IDL.Nat,
  'receiver' : IDL.Principal,
});
export const DashboardStats = IDL.Record({
  'active' : IDL.Nat,
  'pending' : IDL.Nat,
  'totalSpend' : IDL.Nat,
  'totalCampaigns' : IDL.Nat,
  'completedCampaigns' : IDL.Nat,
});
export const BrandProfile = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'industry' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'creator' : IDL.Null,
  'brand' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'createdAt' : IDL.Int,
  'role' : UserRole,
  'email' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'browseCreators' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Vec(CreatorProfile)],
      ['query'],
    ),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createCollaborationRequest' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [CollaborationRequest],
      [],
    ),
  'createPaymentTransaction' : IDL.Func(
      [IDL.Principal, IDL.Nat],
      [PaymentTransaction],
      [],
    ),
  'getBrandDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getBrandProfile' : IDL.Func([], [BrandProfile], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getCollaborationRequest' : IDL.Func(
      [IDL.Nat],
      [CollaborationRequest],
      ['query'],
    ),
  'getCreatorById' : IDL.Func([IDL.Principal], [CreatorProfile], ['query']),
  'getCreatorDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getCreatorProfile' : IDL.Func([], [CreatorProfile], ['query']),
  'getPaymentTransaction' : IDL.Func(
      [IDL.Nat],
      [PaymentTransaction],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'registerBrand' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'registerCreator' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Opt(IDL.Nat),
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        SocialMediaLinks,
        IDL.Opt(ExternalBlob),
      ],
      [CreatorProfile],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCollaborationStatus' : IDL.Func(
      [
        IDL.Nat,
        IDL.Variant({
          'pending' : IDL.Null,
          'completed' : IDL.Null,
          'rejected' : IDL.Null,
          'accepted' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
  'updateCreatorProfile' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Opt(IDL.Nat),
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        SocialMediaLinks,
        IDL.Opt(ExternalBlob),
      ],
      [CreatorProfile],
      [],
    ),
  'updatePaymentStatus' : IDL.Func(
      [
        IDL.Nat,
        IDL.Variant({
          'pending' : IDL.Null,
          'completed' : IDL.Null,
          'failed' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SocialMediaLinks = IDL.Record({
    'tiktok' : IDL.Opt(IDL.Text),
    'twitter' : IDL.Opt(IDL.Text),
    'instagram' : IDL.Opt(IDL.Text),
    'others' : IDL.Opt(IDL.Vec(IDL.Text)),
    'facebook' : IDL.Opt(IDL.Text),
    'youtube' : IDL.Opt(IDL.Text),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CreatorProfile = IDL.Record({
    'id' : IDL.Principal,
    'instagramFollowers' : IDL.Nat,
    'youtubeSubscribers' : IDL.Nat,
    'pricingPost' : IDL.Nat,
    'pricingReel' : IDL.Nat,
    'createdAt' : IDL.Int,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'socialMediaLinks' : SocialMediaLinks,
    'category' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'profilePicture' : IDL.Opt(ExternalBlob),
    'pricingVideo' : IDL.Nat,
    'tiktokFollowers' : IDL.Opt(IDL.Nat),
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const CollaborationRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'completed' : IDL.Null,
      'rejected' : IDL.Null,
      'accepted' : IDL.Null,
    }),
    'creator' : IDL.Principal,
    'createdAt' : IDL.Int,
    'campaignDetails' : IDL.Text,
    'brand' : IDL.Principal,
  });
  const PaymentTransaction = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'completed' : IDL.Null,
      'failed' : IDL.Null,
    }),
    'createdAt' : IDL.Int,
    'sender' : IDL.Principal,
    'amount' : IDL.Nat,
    'receiver' : IDL.Principal,
  });
  const DashboardStats = IDL.Record({
    'active' : IDL.Nat,
    'pending' : IDL.Nat,
    'totalSpend' : IDL.Nat,
    'totalCampaigns' : IDL.Nat,
    'completedCampaigns' : IDL.Nat,
  });
  const BrandProfile = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'industry' : IDL.Text,
  });
  const UserRole = IDL.Variant({ 'creator' : IDL.Null, 'brand' : IDL.Null });
  const UserProfile = IDL.Record({
    'createdAt' : IDL.Int,
    'role' : UserRole,
    'email' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'browseCreators' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Vec(CreatorProfile)],
        ['query'],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createCollaborationRequest' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [CollaborationRequest],
        [],
      ),
    'createPaymentTransaction' : IDL.Func(
        [IDL.Principal, IDL.Nat],
        [PaymentTransaction],
        [],
      ),
    'getBrandDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getBrandProfile' : IDL.Func([], [BrandProfile], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getCollaborationRequest' : IDL.Func(
        [IDL.Nat],
        [CollaborationRequest],
        ['query'],
      ),
    'getCreatorById' : IDL.Func([IDL.Principal], [CreatorProfile], ['query']),
    'getCreatorDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getCreatorProfile' : IDL.Func([], [CreatorProfile], ['query']),
    'getPaymentTransaction' : IDL.Func(
        [IDL.Nat],
        [PaymentTransaction],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'registerBrand' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'registerCreator' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Opt(IDL.Nat),
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          SocialMediaLinks,
          IDL.Opt(ExternalBlob),
        ],
        [CreatorProfile],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCollaborationStatus' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({
            'pending' : IDL.Null,
            'completed' : IDL.Null,
            'rejected' : IDL.Null,
            'accepted' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
    'updateCreatorProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Opt(IDL.Nat),
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          SocialMediaLinks,
          IDL.Opt(ExternalBlob),
        ],
        [CreatorProfile],
        [],
      ),
    'updatePaymentStatus' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({
            'pending' : IDL.Null,
            'completed' : IDL.Null,
            'failed' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };