/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BrandProfile {
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'industry' : string,
}
export interface CollaborationRequest {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'completed' : null } |
    { 'rejected' : null } |
    { 'accepted' : null },
  'creator' : Principal,
  'createdAt' : bigint,
  'campaignDetails' : string,
  'brand' : Principal,
}
export interface CreatorProfile {
  'id' : Principal,
  'instagramFollowers' : bigint,
  'youtubeSubscribers' : bigint,
  'pricingPost' : bigint,
  'pricingReel' : bigint,
  'createdAt' : bigint,
  'fullName' : string,
  'email' : string,
  'socialMediaLinks' : SocialMediaLinks,
  'category' : string,
  'phoneNumber' : string,
  'profilePicture' : [] | [ExternalBlob],
  'pricingVideo' : bigint,
  'tiktokFollowers' : [] | [bigint],
}
export interface DashboardStats {
  'active' : bigint,
  'pending' : bigint,
  'totalSpend' : bigint,
  'totalCampaigns' : bigint,
  'completedCampaigns' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface PaymentTransaction {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'completed' : null } |
    { 'failed' : null },
  'createdAt' : bigint,
  'sender' : Principal,
  'amount' : bigint,
  'receiver' : Principal,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface SocialMediaLinks {
  'tiktok' : [] | [string],
  'twitter' : [] | [string],
  'instagram' : [] | [string],
  'others' : [] | [Array<string>],
  'facebook' : [] | [string],
  'youtube' : [] | [string],
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'createdAt' : bigint,
  'role' : UserRole,
  'email' : string,
}
export type UserRole = { 'creator' : null } |
  { 'brand' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'browseCreators' : ActorMethod<
    [
      [] | [string],
      [] | [bigint],
      [] | [bigint],
      [] | [bigint],
      [] | [bigint],
      [] | [string],
    ],
    Array<CreatorProfile>
  >,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createCollaborationRequest' : ActorMethod<
    [Principal, string],
    CollaborationRequest
  >,
  'createPaymentTransaction' : ActorMethod<
    [Principal, bigint],
    PaymentTransaction
  >,
  'getBrandDashboardStats' : ActorMethod<[], DashboardStats>,
  'getBrandProfile' : ActorMethod<[], BrandProfile>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getCollaborationRequest' : ActorMethod<[bigint], CollaborationRequest>,
  'getCreatorById' : ActorMethod<[Principal], CreatorProfile>,
  'getCreatorDashboardStats' : ActorMethod<[], DashboardStats>,
  'getCreatorProfile' : ActorMethod<[], CreatorProfile>,
  'getPaymentTransaction' : ActorMethod<[bigint], PaymentTransaction>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'registerBrand' : ActorMethod<[string, string, string], undefined>,
  'registerCreator' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      bigint,
      [] | [bigint],
      bigint,
      bigint,
      bigint,
      string,
      SocialMediaLinks,
      [] | [ExternalBlob],
    ],
    CreatorProfile
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCollaborationStatus' : ActorMethod<
    [
      bigint,
      { 'pending' : null } |
        { 'completed' : null } |
        { 'rejected' : null } |
        { 'accepted' : null },
    ],
    undefined
  >,
  'updateCreatorProfile' : ActorMethod<
    [
      string,
      string,
      bigint,
      bigint,
      [] | [bigint],
      bigint,
      bigint,
      bigint,
      string,
      SocialMediaLinks,
      [] | [ExternalBlob],
    ],
    CreatorProfile
  >,
  'updatePaymentStatus' : ActorMethod<
    [
      bigint,
      { 'pending' : null } |
        { 'completed' : null } |
        { 'failed' : null },
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];