/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface BrandProfile {
    name: string;
    createdAt: bigint;
    email: string;
    industry: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface SocialMediaLinks {
    tiktok?: string;
    twitter?: string;
    instagram?: string;
    others?: Array<string>;
    facebook?: string;
    youtube?: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface PaymentTransaction {
    id: bigint;
    status: Variant_pending_completed_failed;
    createdAt: bigint;
    sender: Principal;
    amount: bigint;
    receiver: Principal;
}
export interface DashboardStats {
    active: bigint;
    pending: bigint;
    totalSpend: bigint;
    totalCampaigns: bigint;
    completedCampaigns: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface CreatorProfile {
    id: Principal;
    instagramFollowers: bigint;
    youtubeSubscribers: bigint;
    pricingPost: bigint;
    pricingReel: bigint;
    createdAt: bigint;
    fullName: string;
    email: string;
    socialMediaLinks: SocialMediaLinks;
    category: string;
    phoneNumber: string;
    profilePicture?: ExternalBlob;
    pricingVideo: bigint;
    tiktokFollowers?: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface CollaborationRequest {
    id: bigint;
    status: Variant_pending_completed_rejected_accepted;
    creator: Principal;
    createdAt: bigint;
    campaignDetails: string;
    brand: Principal;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface UserProfile {
    createdAt: bigint;
    role: UserRole;
    email: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    creator = "creator",
    brand = "brand"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_pending_completed_failed {
    pending = "pending",
    completed = "completed",
    failed = "failed"
}
export enum Variant_pending_completed_rejected_accepted {
    pending = "pending",
    completed = "completed",
    rejected = "rejected",
    accepted = "accepted"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    browseCreators(platform: string | null, minFollowers: bigint | null, maxFollowers: bigint | null, minPrice: bigint | null, maxPrice: bigint | null, category: string | null): Promise<Array<CreatorProfile>>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createCollaborationRequest(creatorId: Principal, campaignDetails: string): Promise<CollaborationRequest>;
    createPaymentTransaction(receiver: Principal, amount: bigint): Promise<PaymentTransaction>;
    getBrandDashboardStats(): Promise<DashboardStats>;
    getBrandProfile(): Promise<BrandProfile>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getCollaborationRequest(collabId: bigint): Promise<CollaborationRequest>;
    getCreatorById(creatorId: Principal): Promise<CreatorProfile>;
    getCreatorDashboardStats(): Promise<DashboardStats>;
    getCreatorProfile(): Promise<CreatorProfile>;
    getPaymentTransaction(transactionId: bigint): Promise<PaymentTransaction>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    registerBrand(name: string, email: string, industry: string): Promise<void>;
    registerCreator(fullName: string, phoneNumber: string, email: string, instagramFollowers: bigint, youtubeSubscribers: bigint, tiktokFollowers: bigint | null, pricingReel: bigint, pricingPost: bigint, pricingVideo: bigint, category: string, socialMediaLinks: SocialMediaLinks, profilePicture: ExternalBlob | null): Promise<CreatorProfile>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateCollaborationStatus(collabId: bigint, status: Variant_pending_completed_rejected_accepted): Promise<void>;
    updateCreatorProfile(fullName: string, phoneNumber: string, instagramFollowers: bigint, youtubeSubscribers: bigint, tiktokFollowers: bigint | null, pricingReel: bigint, pricingPost: bigint, pricingVideo: bigint, category: string, socialMediaLinks: SocialMediaLinks, profilePicture: ExternalBlob | null): Promise<CreatorProfile>;
    updatePaymentStatus(transactionId: bigint, status: Variant_pending_completed_failed): Promise<void>;
}
import type { CollaborationRequest as _CollaborationRequest, CreatorProfile as _CreatorProfile, ExternalBlob as _ExternalBlob, PaymentTransaction as _PaymentTransaction, SocialMediaLinks as _SocialMediaLinks, StripeSessionStatus as _StripeSessionStatus, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async browseCreators(arg0: string | null, arg1: bigint | null, arg2: bigint | null, arg3: bigint | null, arg4: bigint | null, arg5: string | null): Promise<Array<CreatorProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.browseCreators(to_candid_opt_n10(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg5));
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.browseCreators(to_candid_opt_n10(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n11(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg5));
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createCollaborationRequest(arg0: Principal, arg1: string): Promise<CollaborationRequest> {
        if (this.processError) {
            try {
                const result = await this.actor.createCollaborationRequest(arg0, arg1);
                return from_candid_CollaborationRequest_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCollaborationRequest(arg0, arg1);
            return from_candid_CollaborationRequest_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPaymentTransaction(arg0: Principal, arg1: bigint): Promise<PaymentTransaction> {
        if (this.processError) {
            try {
                const result = await this.actor.createPaymentTransaction(arg0, arg1);
                return from_candid_PaymentTransaction_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPaymentTransaction(arg0, arg1);
            return from_candid_PaymentTransaction_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBrandDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getBrandDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBrandDashboardStats();
            return result;
        }
    }
    async getBrandProfile(): Promise<BrandProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getBrandProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBrandProfile();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCollaborationRequest(arg0: bigint): Promise<CollaborationRequest> {
        if (this.processError) {
            try {
                const result = await this.actor.getCollaborationRequest(arg0);
                return from_candid_CollaborationRequest_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCollaborationRequest(arg0);
            return from_candid_CollaborationRequest_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCreatorById(arg0: Principal): Promise<CreatorProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getCreatorById(arg0);
                return from_candid_CreatorProfile_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCreatorById(arg0);
            return from_candid_CreatorProfile_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCreatorDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getCreatorDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCreatorDashboardStats();
            return result;
        }
    }
    async getCreatorProfile(): Promise<CreatorProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getCreatorProfile();
                return from_candid_CreatorProfile_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCreatorProfile();
            return from_candid_CreatorProfile_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaymentTransaction(arg0: bigint): Promise<PaymentTransaction> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentTransaction(arg0);
                return from_candid_PaymentTransaction_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentTransaction(arg0);
            return from_candid_PaymentTransaction_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async registerBrand(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerBrand(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerBrand(arg0, arg1, arg2);
            return result;
        }
    }
    async registerCreator(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: bigint | null, arg6: bigint, arg7: bigint, arg8: bigint, arg9: string, arg10: SocialMediaLinks, arg11: ExternalBlob | null): Promise<CreatorProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.registerCreator(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9, to_candid_SocialMediaLinks_n37(this._uploadFile, this._downloadFile, arg10), await to_candid_opt_n39(this._uploadFile, this._downloadFile, arg11));
                return from_candid_CreatorProfile_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerCreator(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9, to_candid_SocialMediaLinks_n37(this._uploadFile, this._downloadFile, arg10), await to_candid_opt_n39(this._uploadFile, this._downloadFile, arg11));
            return from_candid_CreatorProfile_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n41(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n41(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateCollaborationStatus(arg0: bigint, arg1: Variant_pending_completed_rejected_accepted): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCollaborationStatus(arg0, to_candid_variant_n45(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCollaborationStatus(arg0, to_candid_variant_n45(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateCreatorProfile(arg0: string, arg1: string, arg2: bigint, arg3: bigint, arg4: bigint | null, arg5: bigint, arg6: bigint, arg7: bigint, arg8: string, arg9: SocialMediaLinks, arg10: ExternalBlob | null): Promise<CreatorProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCreatorProfile(arg0, arg1, arg2, arg3, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, arg8, to_candid_SocialMediaLinks_n37(this._uploadFile, this._downloadFile, arg9), await to_candid_opt_n39(this._uploadFile, this._downloadFile, arg10));
                return from_candid_CreatorProfile_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCreatorProfile(arg0, arg1, arg2, arg3, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, arg8, to_candid_SocialMediaLinks_n37(this._uploadFile, this._downloadFile, arg9), await to_candid_opt_n39(this._uploadFile, this._downloadFile, arg10));
            return from_candid_CreatorProfile_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePaymentStatus(arg0: bigint, arg1: Variant_pending_completed_failed): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePaymentStatus(arg0, to_candid_variant_n46(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePaymentStatus(arg0, to_candid_variant_n46(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_CollaborationRequest_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CollaborationRequest): CollaborationRequest {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
async function from_candid_CreatorProfile_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreatorProfile): Promise<CreatorProfile> {
    return await from_candid_record_n14(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_PaymentTransaction_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentTransaction): PaymentTransaction {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_SocialMediaLinks_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SocialMediaLinks): SocialMediaLinks {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<string>]): Array<string> | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    instagramFollowers: bigint;
    youtubeSubscribers: bigint;
    pricingPost: bigint;
    pricingReel: bigint;
    createdAt: bigint;
    fullName: string;
    email: string;
    socialMediaLinks: _SocialMediaLinks;
    category: string;
    phoneNumber: string;
    profilePicture: [] | [_ExternalBlob];
    pricingVideo: bigint;
    tiktokFollowers: [] | [bigint];
}): Promise<{
    id: Principal;
    instagramFollowers: bigint;
    youtubeSubscribers: bigint;
    pricingPost: bigint;
    pricingReel: bigint;
    createdAt: bigint;
    fullName: string;
    email: string;
    socialMediaLinks: SocialMediaLinks;
    category: string;
    phoneNumber: string;
    profilePicture?: ExternalBlob;
    pricingVideo: bigint;
    tiktokFollowers?: bigint;
}> {
    return {
        id: value.id,
        instagramFollowers: value.instagramFollowers,
        youtubeSubscribers: value.youtubeSubscribers,
        pricingPost: value.pricingPost,
        pricingReel: value.pricingReel,
        createdAt: value.createdAt,
        fullName: value.fullName,
        email: value.email,
        socialMediaLinks: from_candid_SocialMediaLinks_n15(_uploadFile, _downloadFile, value.socialMediaLinks),
        category: value.category,
        phoneNumber: value.phoneNumber,
        profilePicture: record_opt_to_undefined(await from_candid_opt_n19(_uploadFile, _downloadFile, value.profilePicture)),
        pricingVideo: value.pricingVideo,
        tiktokFollowers: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.tiktokFollowers))
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tiktok: [] | [string];
    twitter: [] | [string];
    instagram: [] | [string];
    others: [] | [Array<string>];
    facebook: [] | [string];
    youtube: [] | [string];
}): {
    tiktok?: string;
    twitter?: string;
    instagram?: string;
    others?: Array<string>;
    facebook?: string;
    youtube?: string;
} {
    return {
        tiktok: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.tiktok)),
        twitter: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.twitter)),
        instagram: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.instagram)),
        others: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.others)),
        facebook: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.facebook)),
        youtube: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.youtube))
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: {
        pending: null;
    } | {
        completed: null;
    } | {
        rejected: null;
    } | {
        accepted: null;
    };
    creator: Principal;
    createdAt: bigint;
    campaignDetails: string;
    brand: Principal;
}): {
    id: bigint;
    status: Variant_pending_completed_rejected_accepted;
    creator: Principal;
    createdAt: bigint;
    campaignDetails: string;
    brand: Principal;
} {
    return {
        id: value.id,
        status: from_candid_variant_n23(_uploadFile, _downloadFile, value.status),
        creator: value.creator,
        createdAt: value.createdAt,
        campaignDetails: value.campaignDetails,
        brand: value.brand
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: {
        pending: null;
    } | {
        completed: null;
    } | {
        failed: null;
    };
    createdAt: bigint;
    sender: Principal;
    amount: bigint;
    receiver: Principal;
}): {
    id: bigint;
    status: Variant_pending_completed_failed;
    createdAt: bigint;
    sender: Principal;
    amount: bigint;
    receiver: Principal;
} {
    return {
        id: value.id,
        status: from_candid_variant_n26(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        sender: value.sender,
        amount: value.amount,
        receiver: value.receiver
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    createdAt: bigint;
    role: _UserRole;
    email: string;
}): {
    createdAt: bigint;
    role: UserRole;
    email: string;
} {
    return {
        createdAt: value.createdAt,
        role: from_candid_UserRole_n30(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    rejected: null;
} | {
    accepted: null;
}): Variant_pending_completed_rejected_accepted {
    return "pending" in value ? Variant_pending_completed_rejected_accepted.pending : "completed" in value ? Variant_pending_completed_rejected_accepted.completed : "rejected" in value ? Variant_pending_completed_rejected_accepted.rejected : "accepted" in value ? Variant_pending_completed_rejected_accepted.accepted : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    failed: null;
}): Variant_pending_completed_failed {
    return "pending" in value ? Variant_pending_completed_failed.pending : "completed" in value ? Variant_pending_completed_failed.completed : "failed" in value ? Variant_pending_completed_failed.failed : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    creator: null;
} | {
    brand: null;
}): UserRole {
    return "creator" in value ? UserRole.creator : "brand" in value ? UserRole.brand : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n36(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
async function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CreatorProfile>): Promise<Array<CreatorProfile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_CreatorProfile_n13(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_SocialMediaLinks_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SocialMediaLinks): _SocialMediaLinks {
    return to_candid_record_n38(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n42(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n40(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tiktok?: string;
    twitter?: string;
    instagram?: string;
    others?: Array<string>;
    facebook?: string;
    youtube?: string;
}): {
    tiktok: [] | [string];
    twitter: [] | [string];
    instagram: [] | [string];
    others: [] | [Array<string>];
    facebook: [] | [string];
    youtube: [] | [string];
} {
    return {
        tiktok: value.tiktok ? candid_some(value.tiktok) : candid_none(),
        twitter: value.twitter ? candid_some(value.twitter) : candid_none(),
        instagram: value.instagram ? candid_some(value.instagram) : candid_none(),
        others: value.others ? candid_some(value.others) : candid_none(),
        facebook: value.facebook ? candid_some(value.facebook) : candid_none(),
        youtube: value.youtube ? candid_some(value.youtube) : candid_none()
    };
}
function to_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    createdAt: bigint;
    role: UserRole;
    email: string;
}): {
    createdAt: bigint;
    role: _UserRole;
    email: string;
} {
    return {
        createdAt: value.createdAt,
        role: to_candid_UserRole_n43(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function to_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    creator: null;
} | {
    brand: null;
} {
    return value == UserRole.creator ? {
        creator: null
    } : value == UserRole.brand ? {
        brand: null
    } : value;
}
function to_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_pending_completed_rejected_accepted): {
    pending: null;
} | {
    completed: null;
} | {
    rejected: null;
} | {
    accepted: null;
} {
    return value == Variant_pending_completed_rejected_accepted.pending ? {
        pending: null
    } : value == Variant_pending_completed_rejected_accepted.completed ? {
        completed: null
    } : value == Variant_pending_completed_rejected_accepted.rejected ? {
        rejected: null
    } : value == Variant_pending_completed_rejected_accepted.accepted ? {
        accepted: null
    } : value;
}
function to_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_pending_completed_failed): {
    pending: null;
} | {
    completed: null;
} | {
    failed: null;
} {
    return value == Variant_pending_completed_failed.pending ? {
        pending: null
    } : value == Variant_pending_completed_failed.completed ? {
        completed: null
    } : value == Variant_pending_completed_failed.failed ? {
        failed: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
